// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCalHistory = "cal_history"

// CalHistory mapped from table <cal_history>
type CalHistory struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Data   string `gorm:"column:data" json:"data"`
	Result string `gorm:"column:result" json:"result"`
	Time   string `gorm:"column:time" json:"time"`
}

// TableName CalHistory's table name
func (*CalHistory) TableName() string {
	return TableNameCalHistory
}
