// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCalRate = "cal_rate"

// CalRate mapped from table <cal_rate>
type CalRate struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Duration string `gorm:"column:duration" json:"duration"`
	Rate     string `gorm:"column:rate" json:"rate"`
	Type     int32  `gorm:"column:type;comment:0 save" json:"type"` // 0 save
	Num      int32  `gorm:"column:num" json:"num"`
}

// TableName CalRate's table name
func (*CalRate) TableName() string {
	return TableNameCalRate
}
