// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDemo = "demo"

// Demo mapped from table <demo>
type Demo struct {
	ID       string `gorm:"column:id;primaryKey" json:"id"`
	Name     string `gorm:"column:name" json:"name"`
	Age      int32  `gorm:"column:age" json:"age"`
	Password string `gorm:"column:password" json:"password"`
}

// TableName Demo's table name
func (*Demo) TableName() string {
	return TableNameDemo
}
