// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQrtzSchedulerState = "qrtz_scheduler_state"

// QrtzSchedulerState mapped from table <qrtz_scheduler_state>
type QrtzSchedulerState struct {
	SchedName       string `gorm:"column:sched_name;primaryKey;comment:调度名称" json:"sched_name"`               // 调度名称
	InstanceName    string `gorm:"column:instance_name;primaryKey;comment:实例名称" json:"instance_name"`         // 实例名称
	LastCheckinTime int64  `gorm:"column:last_checkin_time;not null;comment:上次检查时间" json:"last_checkin_time"` // 上次检查时间
	CheckinInterval int64  `gorm:"column:checkin_interval;not null;comment:检查间隔时间" json:"checkin_interval"`   // 检查间隔时间
}

// TableName QrtzSchedulerState's table name
func (*QrtzSchedulerState) TableName() string {
	return TableNameQrtzSchedulerState
}
