// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQrtzLock = "qrtz_locks"

// QrtzLock mapped from table <qrtz_locks>
type QrtzLock struct {
	SchedName string `gorm:"column:sched_name;primaryKey;comment:调度名称" json:"sched_name"` // 调度名称
	LockName  string `gorm:"column:lock_name;primaryKey;comment:悲观锁名称" json:"lock_name"`  // 悲观锁名称
}

// TableName QrtzLock's table name
func (*QrtzLock) TableName() string {
	return TableNameQrtzLock
}
