// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQrtzSimpleTrigger = "qrtz_simple_triggers"

// QrtzSimpleTrigger mapped from table <qrtz_simple_triggers>
type QrtzSimpleTrigger struct {
	SchedName      string `gorm:"column:sched_name;primaryKey;comment:调度名称" json:"sched_name"`                                 // 调度名称
	TriggerName    string `gorm:"column:trigger_name;primaryKey;comment:qrtz_triggers表trigger_name的外键" json:"trigger_name"`    // qrtz_triggers表trigger_name的外键
	TriggerGroup   string `gorm:"column:trigger_group;primaryKey;comment:qrtz_triggers表trigger_group的外键" json:"trigger_group"` // qrtz_triggers表trigger_group的外键
	RepeatCount    int64  `gorm:"column:repeat_count;not null;comment:重复的次数统计" json:"repeat_count"`                            // 重复的次数统计
	RepeatInterval int64  `gorm:"column:repeat_interval;not null;comment:重复的间隔时间" json:"repeat_interval"`                      // 重复的间隔时间
	TimesTriggered int64  `gorm:"column:times_triggered;not null;comment:已经触发的次数" json:"times_triggered"`                      // 已经触发的次数
}

// TableName QrtzSimpleTrigger's table name
func (*QrtzSimpleTrigger) TableName() string {
	return TableNameQrtzSimpleTrigger
}
