// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQrtzPausedTriggerGrp = "qrtz_paused_trigger_grps"

// QrtzPausedTriggerGrp mapped from table <qrtz_paused_trigger_grps>
type QrtzPausedTriggerGrp struct {
	SchedName    string `gorm:"column:sched_name;primaryKey;comment:调度名称" json:"sched_name"`                                 // 调度名称
	TriggerGroup string `gorm:"column:trigger_group;primaryKey;comment:qrtz_triggers表trigger_group的外键" json:"trigger_group"` // qrtz_triggers表trigger_group的外键
}

// TableName QrtzPausedTriggerGrp's table name
func (*QrtzPausedTriggerGrp) TableName() string {
	return TableNameQrtzPausedTriggerGrp
}
