// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQrtzBlobTrigger = "qrtz_blob_triggers"

// QrtzBlobTrigger mapped from table <qrtz_blob_triggers>
type QrtzBlobTrigger struct {
	SchedName    string `gorm:"column:sched_name;primaryKey;comment:调度名称" json:"sched_name"`                                 // 调度名称
	TriggerName  string `gorm:"column:trigger_name;primaryKey;comment:qrtz_triggers表trigger_name的外键" json:"trigger_name"`    // qrtz_triggers表trigger_name的外键
	TriggerGroup string `gorm:"column:trigger_group;primaryKey;comment:qrtz_triggers表trigger_group的外键" json:"trigger_group"` // qrtz_triggers表trigger_group的外键
	BlobData     []byte `gorm:"column:blob_data;comment:存放持久化Trigger对象" json:"blob_data"`                                    // 存放持久化Trigger对象
}

// TableName QrtzBlobTrigger's table name
func (*QrtzBlobTrigger) TableName() string {
	return TableNameQrtzBlobTrigger
}
