// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQrtzTrigger = "qrtz_triggers"

// QrtzTrigger mapped from table <qrtz_triggers>
type QrtzTrigger struct {
	SchedName    string `gorm:"column:sched_name;primaryKey;comment:调度名称" json:"sched_name"`                      // 调度名称
	TriggerName  string `gorm:"column:trigger_name;primaryKey;comment:触发器的名字" json:"trigger_name"`                // 触发器的名字
	TriggerGroup string `gorm:"column:trigger_group;primaryKey;comment:触发器所属组的名字" json:"trigger_group"`           // 触发器所属组的名字
	JobName      string `gorm:"column:job_name;not null;comment:qrtz_job_details表job_name的外键" json:"job_name"`    // qrtz_job_details表job_name的外键
	JobGroup     string `gorm:"column:job_group;not null;comment:qrtz_job_details表job_group的外键" json:"job_group"` // qrtz_job_details表job_group的外键
	Description  string `gorm:"column:description;comment:相关介绍" json:"description"`                               // 相关介绍
	NextFireTime int64  `gorm:"column:next_fire_time;comment:上一次触发时间（毫秒）" json:"next_fire_time"`                  // 上一次触发时间（毫秒）
	PrevFireTime int64  `gorm:"column:prev_fire_time;comment:下一次触发时间（默认为-1表示不触发）" json:"prev_fire_time"`          // 下一次触发时间（默认为-1表示不触发）
	Priority     int32  `gorm:"column:priority;comment:优先级" json:"priority"`                                      // 优先级
	TriggerState string `gorm:"column:trigger_state;not null;comment:触发器状态" json:"trigger_state"`                 // 触发器状态
	TriggerType  string `gorm:"column:trigger_type;not null;comment:触发器的类型" json:"trigger_type"`                  // 触发器的类型
	StartTime    int64  `gorm:"column:start_time;not null;comment:开始时间" json:"start_time"`                        // 开始时间
	EndTime      int64  `gorm:"column:end_time;comment:结束时间" json:"end_time"`                                     // 结束时间
	CalendarName string `gorm:"column:calendar_name;comment:日程表名称" json:"calendar_name"`                          // 日程表名称
	MisfireInstr int32  `gorm:"column:misfire_instr;comment:补偿执行的策略" json:"misfire_instr"`                        // 补偿执行的策略
	JobData      []byte `gorm:"column:job_data;comment:存放持久化job对象" json:"job_data"`                               // 存放持久化job对象
}

// TableName QrtzTrigger's table name
func (*QrtzTrigger) TableName() string {
	return TableNameQrtzTrigger
}
