// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQrtzCronTrigger = "qrtz_cron_triggers"

// QrtzCronTrigger mapped from table <qrtz_cron_triggers>
type QrtzCronTrigger struct {
	SchedName      string `gorm:"column:sched_name;primaryKey;comment:调度名称" json:"sched_name"`                                 // 调度名称
	TriggerName    string `gorm:"column:trigger_name;primaryKey;comment:qrtz_triggers表trigger_name的外键" json:"trigger_name"`    // qrtz_triggers表trigger_name的外键
	TriggerGroup   string `gorm:"column:trigger_group;primaryKey;comment:qrtz_triggers表trigger_group的外键" json:"trigger_group"` // qrtz_triggers表trigger_group的外键
	CronExpression string `gorm:"column:cron_expression;not null;comment:cron表达式" json:"cron_expression"`                      // cron表达式
	TimeZoneID     string `gorm:"column:time_zone_id;comment:时区" json:"time_zone_id"`                                          // 时区
}

// TableName QrtzCronTrigger's table name
func (*QrtzCronTrigger) TableName() string {
	return TableNameQrtzCronTrigger
}
