// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQrtzCalendar = "qrtz_calendars"

// QrtzCalendar mapped from table <qrtz_calendars>
type QrtzCalendar struct {
	SchedName    string `gorm:"column:sched_name;primaryKey;comment:调度名称" json:"sched_name"`       // 调度名称
	CalendarName string `gorm:"column:calendar_name;primaryKey;comment:日历名称" json:"calendar_name"` // 日历名称
	Calendar     []byte `gorm:"column:calendar;not null;comment:存放持久化calendar对象" json:"calendar"`  // 存放持久化calendar对象
}

// TableName QrtzCalendar's table name
func (*QrtzCalendar) TableName() string {
	return TableNameQrtzCalendar
}
