// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQrtzJobDetail = "qrtz_job_details"

// QrtzJobDetail mapped from table <qrtz_job_details>
type QrtzJobDetail struct {
	SchedName        string `gorm:"column:sched_name;primaryKey;comment:调度名称" json:"sched_name"`                 // 调度名称
	JobName          string `gorm:"column:job_name;primaryKey;comment:任务名称" json:"job_name"`                     // 任务名称
	JobGroup         string `gorm:"column:job_group;primaryKey;comment:任务组名" json:"job_group"`                   // 任务组名
	Description      string `gorm:"column:description;comment:相关介绍" json:"description"`                          // 相关介绍
	JobClassName     string `gorm:"column:job_class_name;not null;comment:执行任务类名称" json:"job_class_name"`        // 执行任务类名称
	IsDurable        string `gorm:"column:is_durable;not null;comment:是否持久化" json:"is_durable"`                  // 是否持久化
	IsNonconcurrent  string `gorm:"column:is_nonconcurrent;not null;comment:是否并发" json:"is_nonconcurrent"`       // 是否并发
	IsUpdateData     string `gorm:"column:is_update_data;not null;comment:是否更新数据" json:"is_update_data"`         // 是否更新数据
	RequestsRecovery string `gorm:"column:requests_recovery;not null;comment:是否接受恢复执行" json:"requests_recovery"` // 是否接受恢复执行
	JobData          []byte `gorm:"column:job_data;comment:存放持久化job对象" json:"job_data"`                          // 存放持久化job对象
}

// TableName QrtzJobDetail's table name
func (*QrtzJobDetail) TableName() string {
	return TableNameQrtzJobDetail
}
