// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQrtzFiredTrigger = "qrtz_fired_triggers"

// QrtzFiredTrigger mapped from table <qrtz_fired_triggers>
type QrtzFiredTrigger struct {
	SchedName        string `gorm:"column:sched_name;primaryKey;comment:调度名称" json:"sched_name"`                               // 调度名称
	EntryID          string `gorm:"column:entry_id;primaryKey;comment:调度器实例id" json:"entry_id"`                                // 调度器实例id
	TriggerName      string `gorm:"column:trigger_name;not null;comment:qrtz_triggers表trigger_name的外键" json:"trigger_name"`    // qrtz_triggers表trigger_name的外键
	TriggerGroup     string `gorm:"column:trigger_group;not null;comment:qrtz_triggers表trigger_group的外键" json:"trigger_group"` // qrtz_triggers表trigger_group的外键
	InstanceName     string `gorm:"column:instance_name;not null;comment:调度器实例名" json:"instance_name"`                         // 调度器实例名
	FiredTime        int64  `gorm:"column:fired_time;not null;comment:触发的时间" json:"fired_time"`                                // 触发的时间
	SchedTime        int64  `gorm:"column:sched_time;not null;comment:定时器制定的时间" json:"sched_time"`                             // 定时器制定的时间
	Priority         int32  `gorm:"column:priority;not null;comment:优先级" json:"priority"`                                      // 优先级
	State            string `gorm:"column:state;not null;comment:状态" json:"state"`                                             // 状态
	JobName          string `gorm:"column:job_name;comment:任务名称" json:"job_name"`                                              // 任务名称
	JobGroup         string `gorm:"column:job_group;comment:任务组名" json:"job_group"`                                            // 任务组名
	IsNonconcurrent  string `gorm:"column:is_nonconcurrent;comment:是否并发" json:"is_nonconcurrent"`                              // 是否并发
	RequestsRecovery string `gorm:"column:requests_recovery;comment:是否接受恢复执行" json:"requests_recovery"`                        // 是否接受恢复执行
}

// TableName QrtzFiredTrigger's table name
func (*QrtzFiredTrigger) TableName() string {
	return TableNameQrtzFiredTrigger
}
