// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQrtzSimpropTrigger = "qrtz_simprop_triggers"

// QrtzSimpropTrigger mapped from table <qrtz_simprop_triggers>
type QrtzSimpropTrigger struct {
	SchedName    string  `gorm:"column:sched_name;primaryKey;comment:调度名称" json:"sched_name"`                                 // 调度名称
	TriggerName  string  `gorm:"column:trigger_name;primaryKey;comment:qrtz_triggers表trigger_name的外键" json:"trigger_name"`    // qrtz_triggers表trigger_name的外键
	TriggerGroup string  `gorm:"column:trigger_group;primaryKey;comment:qrtz_triggers表trigger_group的外键" json:"trigger_group"` // qrtz_triggers表trigger_group的外键
	StrProp1     string  `gorm:"column:str_prop_1;comment:String类型的trigger的第一个参数" json:"str_prop_1"`                          // String类型的trigger的第一个参数
	StrProp2     string  `gorm:"column:str_prop_2;comment:String类型的trigger的第二个参数" json:"str_prop_2"`                          // String类型的trigger的第二个参数
	StrProp3     string  `gorm:"column:str_prop_3;comment:String类型的trigger的第三个参数" json:"str_prop_3"`                          // String类型的trigger的第三个参数
	IntProp1     int32   `gorm:"column:int_prop_1;comment:int类型的trigger的第一个参数" json:"int_prop_1"`                             // int类型的trigger的第一个参数
	IntProp2     int32   `gorm:"column:int_prop_2;comment:int类型的trigger的第二个参数" json:"int_prop_2"`                             // int类型的trigger的第二个参数
	LongProp1    int64   `gorm:"column:long_prop_1;comment:long类型的trigger的第一个参数" json:"long_prop_1"`                          // long类型的trigger的第一个参数
	LongProp2    int64   `gorm:"column:long_prop_2;comment:long类型的trigger的第二个参数" json:"long_prop_2"`                          // long类型的trigger的第二个参数
	DecProp1     float64 `gorm:"column:dec_prop_1;comment:decimal类型的trigger的第一个参数" json:"dec_prop_1"`                         // decimal类型的trigger的第一个参数
	DecProp2     float64 `gorm:"column:dec_prop_2;comment:decimal类型的trigger的第二个参数" json:"dec_prop_2"`                         // decimal类型的trigger的第二个参数
	BoolProp1    string  `gorm:"column:bool_prop_1;comment:Boolean类型的trigger的第一个参数" json:"bool_prop_1"`                       // Boolean类型的trigger的第一个参数
	BoolProp2    string  `gorm:"column:bool_prop_2;comment:Boolean类型的trigger的第二个参数" json:"bool_prop_2"`                       // Boolean类型的trigger的第二个参数
}

// TableName QrtzSimpropTrigger's table name
func (*QrtzSimpropTrigger) TableName() string {
	return TableNameQrtzSimpropTrigger
}
