// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameZxApproval = "zx_approval"

// ZxApproval mapped from table <zx_approval>
type ZxApproval struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreateTime   time.Time `gorm:"column:create_time" json:"create_time"`
	Creator      string    `gorm:"column:creator" json:"creator"`
	Status       int32     `gorm:"column:status" json:"status"`
	Type         int32     `gorm:"column:type" json:"type"`
	ApprovalUser string    `gorm:"column:approval_user" json:"approval_user"`
	InvID        int32     `gorm:"column:inv_id" json:"inv_id"`
	TicketID     int32     `gorm:"column:ticket_id" json:"ticket_id"`
	ApprovalID   int32     `gorm:"column:approval_id" json:"approval_id"`
}

// TableName ZxApproval's table name
func (*ZxApproval) TableName() string {
	return TableNameZxApproval
}
