// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameZxBom = "zx_bom"

// ZxBom mapped from table <zx_bom>
type ZxBom struct {
	ID                 int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`       // 主键
	SerialNumber       string `gorm:"column:serial_number;comment:序号" json:"serial_number"`               // 序号
	StockName          string `gorm:"column:stock_name;comment:存货名称" json:"stock_name"`                   // 存货名称
	ShowName           string `gorm:"column:show_name;comment:显示名称" json:"show_name"`                     // 显示名称
	PcbName            string `gorm:"column:pcb_name;comment:PCB名称" json:"pcb_name"`                      // PCB名称
	Quantity           string `gorm:"column:quantity;comment:数量" json:"quantity"`                         // 数量
	StockCode          string `gorm:"column:stock_code;comment:存货编码" json:"stock_code"`                   // 存货编码
	ManufacturerModel  string `gorm:"column:manufacturer_model;comment:厂商型号" json:"manufacturer_model"`   // 厂商型号
	Manufacturer       string `gorm:"column:manufacturer;comment:厂商" json:"manufacturer"`                 // 厂商
	InventoryLevel     string `gorm:"column:inventory_level;comment:存货优选等级" json:"inventory_level"`       // 存货优选等级
	InventoryStatement string `gorm:"column:inventory_statement;comment:存货说明" json:"inventory_statement"` // 存货说明
	SubstituteMaterial string `gorm:"column:substitute_material;comment:替代料" json:"substitute_material"`  // 替代料
	Remark             string `gorm:"column:remark;comment:备注" json:"remark"`                             // 备注
	FileName           string `gorm:"column:file_name;comment:文件名称" json:"file_name"`                     // 文件名称
	CreateTime         string `gorm:"column:create_time;comment:文件创建时间" json:"create_time"`               // 文件创建时间
	Designator         string `gorm:"column:designator;comment:位号" json:"designator"`                     // 位号
}

// TableName ZxBom's table name
func (*ZxBom) TableName() string {
	return TableNameZxBom
}
