// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameZxFile = "zx_file"

// ZxFile mapped from table <zx_file>
type ZxFile struct {
	ID       int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MapName  string    `gorm:"column:map_name" json:"map_name"`
	MapPath  string    `gorm:"column:map_path" json:"map_path"`
	PcbName  string    `gorm:"column:pcb_name" json:"pcb_name"`
	PcbPath  string    `gorm:"column:pcb_path" json:"pcb_path"`
	Type     int32     `gorm:"column:type" json:"type"`
	Status   int32     `gorm:"column:status" json:"status"`
	Msg      string    `gorm:"column:msg" json:"msg"`
	Version  time.Time `gorm:"column:version" json:"version"`
	Uploader string    `gorm:"column:uploader" json:"uploader"`
	IsShow   int32     `gorm:"column:is_show" json:"is_show"`
	RealName string    `gorm:"column:real_name" json:"real_name"`
	Vnumber  string    `gorm:"column:vnumber;comment:版本号" json:"vnumber"` // 版本号
}

// TableName ZxFile's table name
func (*ZxFile) TableName() string {
	return TableNameZxFile
}
