// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameZxInvmore = "zx_invmore"

// ZxInvmore mapped from table <zx_invmore>
type ZxInvmore struct {
	ID             int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Code           string `gorm:"column:code" json:"code"`
	Name           string `gorm:"column:name" json:"name"`
	Manufacturer   string `gorm:"column:manufacturer" json:"manufacturer"`
	Model          string `gorm:"column:model" json:"model"`
	MnemonicCode   string `gorm:"column:mnemonic_code" json:"mnemonic_code"`
	CategoryCode   string `gorm:"column:category_code" json:"category_code"`
	CategoryName   string `gorm:"column:category_name" json:"category_name"`
	PreferredGrade string `gorm:"column:preferred_grade" json:"preferred_grade"`
	Description    string `gorm:"column:description" json:"description"`
	FileName       string `gorm:"column:file_name" json:"file_name"`
	FilePath       string `gorm:"column:file_path" json:"file_path"`
	FileType       string `gorm:"column:file_type" json:"file_type"`
	Param          string `gorm:"column:param" json:"param"`
	Value          string `gorm:"column:value" json:"value"`
	LibraryPath    string `gorm:"column:library_path" json:"library_path"`
	FootprintRef   string `gorm:"column:footprint_ref" json:"footprint_ref"`
	FootprintPath  string `gorm:"column:footprint_path" json:"footprint_path"`
	IsU8           int32  `gorm:"column:is_u8" json:"is_u8"`
	LibraryRef     string `gorm:"column:library_ref" json:"library_ref"`
	MapName        string `gorm:"column:map_name" json:"map_name"`
	MapPath        string `gorm:"column:map_path" json:"map_path"`
	PcbName        string `gorm:"column:pcb_name" json:"pcb_name"`
	PcbPath        string `gorm:"column:pcb_path" json:"pcb_path"`
	TicketID       int32  `gorm:"column:ticket_id" json:"ticket_id"`
	Status         int32  `gorm:"column:status" json:"status"`
	PackageName    string `gorm:"column:package_name" json:"package_name"`
	DisplayName    string `gorm:"column:display_name" json:"display_name"`
	ChooseType     string `gorm:"column:choose_type" json:"choose_type"`
	InvClassCode   string `gorm:"column:inv_class_code" json:"inv_class_code"`
	InvClassName   string `gorm:"column:inv_class_name" json:"inv_class_name"`
}

// TableName ZxInvmore's table name
func (*ZxInvmore) TableName() string {
	return TableNameZxInvmore
}
