// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameZxInvClass = "zx_inv_class"

// ZxInvClass mapped from table <zx_inv_class>
type ZxInvClass struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Code  string `gorm:"column:code" json:"code"`
	Name  string `gorm:"column:name" json:"name"`
	Grade int32  `gorm:"column:grade" json:"grade"`
	End   int32  `gorm:"column:end" json:"end"`
}

// TableName ZxInvClass's table name
func (*ZxInvClass) TableName() string {
	return TableNameZxInvClass
}
