// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameZxPermission = "zx_permission"

// ZxPermission mapped from table <zx_permission>
type ZxPermission struct {
	ID         int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RoleID     int32 `gorm:"column:role_id" json:"role_id"`
	Permission int32 `gorm:"column:permission" json:"permission"`
}

// TableName ZxPermission's table name
func (*ZxPermission) TableName() string {
	return TableNameZxPermission
}
