// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameZxTicket = "zx_ticket"

// ZxTicket mapped from table <zx_ticket>
type ZxTicket struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TicketCode  string    `gorm:"column:ticket_code" json:"ticket_code"`
	TicketMaker string    `gorm:"column:ticket_maker" json:"ticket_maker"`
	CreateTime  time.Time `gorm:"column:create_time" json:"create_time"`
	Status      int32     `gorm:"column:status" json:"status"`
	Remark      string    `gorm:"column:remark" json:"remark"`
}

// TableName ZxTicket's table name
func (*ZxTicket) TableName() string {
	return TableNameZxTicket
}
