// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameZxU8 = "zx_u8"

// ZxU8 mapped from table <zx_u8>
type ZxU8 struct {
	Value         string `gorm:"column:Value" json:"Value"`
	EncodeNumber  string `gorm:"column:Encode Number;primaryKey" json:"Encode Number"`
	Mpn           string `gorm:"column:Mpn" json:"Mpn"`
	Name          string `gorm:"column:Name" json:"Name"`
	Brand         string `gorm:"column:Brand" json:"Brand"`
	Parameter     string `gorm:"column:Parameter" json:"Parameter"`
	Grade         string `gorm:"column:Grade" json:"Grade"`
	LibraryRef    string `gorm:"column:Library Ref" json:"Library Ref"`
	LibraryPath   string `gorm:"column:Library Path" json:"Library Path"`
	FootprintRef  string `gorm:"column:Footprint Ref" json:"Footprint Ref"`
	FootprintPath string `gorm:"column:Footprint Path" json:"Footprint Path"`
	Description   string `gorm:"column:description" json:"description"`
	MnemonicCode  string `gorm:"column:Mnemonic Code" json:"Mnemonic Code"`
	PackageName   string `gorm:"column:Package Name" json:"Package Name"`
	Type          string `gorm:"column:Type" json:"Type"`
}

// TableName ZxU8's table name
func (*ZxU8) TableName() string {
	return TableNameZxU8
}
